[package]
name = "codspeed-divan-compat"
version = "2.10.0"
rust-version = "1.80"
edition = "2021"
description = "Divan compatibility layer for CodSpeed"
authors = ["Arthur Pastel <arthur@codspeed.io>"]
documentation = "https://docs.codspeed.io"
readme = "README.md"
repository = "https://github.com/CodSpeedHQ/codspeed-rust"
homepage = "https://codspeed.io"
license = "MIT OR Apache-2.0"
categories = [
  "development-tools",
  "development-tools::profiling",
  "development-tools::testing",
]
keywords = ["codspeed", "benchmark", "divan"]

[dependencies]
codspeed = { path = "../codspeed", version = "=2.10.0" }
divan = { package = "codspeed-divan-compat-walltime", path = "./divan_fork", version = "=2.10.0" }
codspeed-divan-compat-macros = { version = "=2.10.0", path = './macros' }

[[bench]]
name = "basic_example"
harness = false
